use schemars::{Schema, schema_for};
use serde::Serialize;

use crate::{
    AuditEvent, BibliographicRecord, CompiledStrategy, NamedFilterPack, NativeSearchStrategy,
    ProviderManifest, ProviderPage, SearchRun, SearchStrategy, SourceReceipt,
};

/// A canonical catalogue entry whose root wire shape is owned by this Rust crate.
///
/// This registry is intentionally explicit. Repository-policy schemas and product-level
/// Searchright contracts are not implied to be generated by the neutral core.
#[derive(Debug, Clone)]
pub struct RustOwnedSchema {
    /// Catalogue identifier from `contracts/schema-catalog.json`.
    pub catalogue_id: &'static str,
    /// Workspace-relative canonical schema path.
    pub canonical_path: &'static str,
    /// Schema generated from the public Rust root type.
    pub generated: Schema,
}

/// Fail-closed declaration of the Rust/canonical schema comparison scope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct RustSchemaParityScope {
    /// Stable report format identifier.
    pub schema_version: &'static str,
    /// Exact byte-or-semantic schema equality is not yet demonstrated.
    pub exact_parity: bool,
    /// Number of explicitly registered Rust-owned roots.
    pub rust_owned_roots: usize,
    /// Semantic dimensions not represented completely by the generated schemas.
    pub known_losses: &'static [&'static str],
    /// Evidence boundary applied to this report.
    pub claim_boundary: &'static str,
}

/// Report the admitted parity scope without promoting structural equality to semantic equality.
#[must_use]
pub fn rust_schema_parity_scope() -> RustSchemaParityScope {
    let rust_owned_roots = rust_owned_schemas().len();
    RustSchemaParityScope {
        schema_version: "org.searchright.rust-schema-parity.v1",
        exact_parity: false,
        rust_owned_roots,
        known_losses: &[
            "additional-properties closure",
            "collection uniqueness",
            "constant schema-version values",
            "field requiredness",
            "field and root types",
            "nested and reference shapes",
            "enum, format and default constraints",
            "numeric ranges",
            "string length constraints",
        ],
        claim_boundary: "This value declares the registered comparison scope only. Root-property-name results require the compiler test receipt; exact constraint and semantic parity remains fail-closed.",
    }
}

/// Generate the neutral-core root schemas currently admitted to parity checking.
#[must_use]
pub fn rust_owned_schemas() -> Vec<RustOwnedSchema> {
    vec![
        entry::<AuditEvent>(
            "audit-event",
            "contracts/json-schema/audit-event.v1.schema.json",
        ),
        entry::<BibliographicRecord>(
            "bibliographic-record",
            "contracts/json-schema/bibliographic-record.v1.schema.json",
        ),
        entry::<CompiledStrategy>(
            "compiled-strategy",
            "contracts/json-schema/compiled-strategy.v1.schema.json",
        ),
        entry::<NamedFilterPack>(
            "named-filter-pack",
            "contracts/json-schema/named-filter-pack.v1.schema.json",
        ),
        entry::<NativeSearchStrategy>(
            "native-search-strategy",
            "contracts/json-schema/native-search-strategy.v1.schema.json",
        ),
        entry::<ProviderManifest>(
            "provider-manifest",
            "contracts/json-schema/provider-manifest.v1.schema.json",
        ),
        entry::<ProviderPage>(
            "provider-page",
            "contracts/json-schema/provider-page.v1.schema.json",
        ),
        entry::<SearchRun>(
            "search-run",
            "contracts/json-schema/search-run.v1.schema.json",
        ),
        entry::<SearchStrategy>(
            "search-strategy",
            "contracts/json-schema/search-strategy.v1.schema.json",
        ),
        entry::<SourceReceipt>(
            "source-receipt",
            "contracts/json-schema/source-receipt.v1.schema.json",
        ),
    ]
}

fn entry<T: schemars::JsonSchema>(
    catalogue_id: &'static str,
    canonical_path: &'static str,
) -> RustOwnedSchema {
    RustOwnedSchema {
        catalogue_id,
        canonical_path,
        generated: schema_for!(T),
    }
}
