coverage:
  precision: 2
  round: down
  range: 80..100
  status:
    project:
      default:
        target: 61%
        threshold: 0%
    patch:
      default:
        target: 83%
        threshold: 0%
comment:
  layout: reach,diff,flags,tree
  behavior: default
  require_changes: true
ignore:
  - "contracts/**"
  - "verification/**"
