cache = true
max_cache_age = "1d"
max_concurrency = 8
retry_wait_time = 2
max_retries = 2
accept = [200, 204, 206, 429]
exclude = [
  "http://localhost",
  "https://example.invalid",
  "searchright://",
]
