// Generated contract-only types. Do not edit by hand.

export type JsonValue = null | boolean | number | string | ReadonlyArray<JsonValue> | { readonly [key: string]: JsonValue };

export type AccessDecision = { readonly "blockers": ReadonlyArray<string>; readonly "human_approval_required": boolean; readonly "permitted": boolean; readonly "request_id": string; readonly "schema_version": "org.searchright.access-decision.v1"; readonly "tenant_id": string; };

export type AccessRequest = { readonly "authenticated": boolean; readonly "external_write": boolean; readonly "final_eligibility_decision": boolean; readonly "human_approval": boolean; readonly "principal_id": string; readonly "principal_kind": "human" | "service" | "agent"; readonly "region": string; readonly "request_id": string; readonly "schema_version": "org.searchright.access-request.v1"; readonly "scopes": ReadonlyArray<"review_read" | "review_write" | "search_execute" | "screening_recommend" | "screening_decide" | "tenant_admin" | "external_write">; readonly "tenant_id": string; };

export type AgentWorkflow = { readonly "schema_version": "org.searchright.agent-workflow.v1"; readonly "screening_authority": "advisory_only" | "include_only" | "exclusion_with_human_confirmation"; readonly "steps": ReadonlyArray<{ readonly "authority": "read_only_automatic" | "human_confirmation" | "explicit_approval" | "role_policy" | "human_only"; readonly "blocking_conditions": ReadonlyArray<string>; readonly "outputs": ReadonlyArray<string>; readonly "required_inputs": ReadonlyArray<string>; readonly "stage": "scope" | "eligibility" | "source_selection" | "strategy_design" | "press_review" | "execute" | "deduplicate" | "title_abstract_screening" | "full_text_screening" | "report" | "update"; }>; };

export type ArchitecturePolicy = { readonly "claim_boundary": string; readonly "default_policy": "deny"; readonly "external_write_scripts": ReadonlyArray<{ readonly "apply_flag": string; readonly "environment_gate": string; readonly "path": string; }>; readonly "final_eligibility_authority_source_roots": ReadonlyArray<string>; readonly "forbidden_dependency_prefixes_for_neutral_crates": ReadonlyArray<string>; readonly "forbidden_internal_edges": ReadonlyArray<{ readonly "from": string; readonly "reason": string; readonly "to": string; }>; readonly "network_dependencies": { readonly [key: string]: ReadonlyArray<string>; }; readonly "neutral_crates": ReadonlyArray<string>; readonly "provider_endpoint_source_roots": ReadonlyArray<string>; readonly "public_package_default": "deny"; readonly "schema_version": "org.searchright.architecture-policy.v1"; };

export type AuditEvent = { readonly "actor": { readonly "actor_id": string; readonly "actor_type": string; readonly "provenance": null | string; }; readonly "event_hash": string; readonly "event_id": string; readonly "event_type": string; readonly "occurred_at": string; readonly "payload": JsonValue; readonly "previous_hash": "GENESIS" | string; readonly "review_id": string; readonly "schema_version": "org.searchright.audit-event.v1"; };

export type AuditEventRegistry = { readonly "claim_boundary": string; readonly "envelope_schema_version": "org.searchright.audit-event.v1"; readonly "event_types": ReadonlyArray<{ readonly "allowed_payload_keys": ReadonlyArray<string>; readonly "current_payload_version": number; readonly "event_type": string; readonly "legacy_unversioned_payload_version": number; readonly "migrations": ReadonlyArray<string>; readonly "payload_field_types": { readonly [key: string]: "boolean" | "integer" | "string"; }; readonly "versions": ReadonlyArray<{ readonly "status": "migration_only" | "current"; readonly "version": number; }>; }>; readonly "maximum_payload_bytes": number; readonly "prohibited_payload_keys": ReadonlyArray<string>; readonly "schema_version": "org.searchright.audit-event-registry.v1"; readonly "unknown_event_type_policy": "reject"; readonly "unknown_payload_version_policy": "reject"; };

export type BackupManifest = { readonly "backup_id": string; readonly "content_classes": ReadonlyArray<string>; readonly "created_at": string; readonly "digest": string; readonly "digest_algorithm": string; readonly "encrypted": boolean; readonly "key_reference": string | null; readonly "kind": "full" | "incremental" | "research_object"; readonly "parent_backup_id": string | null; readonly "restore_test_required": boolean; readonly "retention_days": number; readonly "schema_version": "org.searchright.backup-manifest.v1"; readonly "scope_id": string; };

export type BenchmarkReportMetric = { readonly "lower_bound": number | null; readonly "name": string; readonly "sample_size": number; readonly "unit": string; readonly "upper_bound": number | null; readonly "value": number; };

export type BenchmarkReport = { readonly "benchmark_id": string; readonly "claim_boundary": string; readonly "configuration_digest": string; readonly "corpus_id": string; readonly "corpus_version": string; readonly "environment": ReadonlyArray<string>; readonly "generated_at": string; readonly "implementation_version": string; readonly "leakage_controls": ReadonlyArray<string>; readonly "metrics": ReadonlyArray<BenchmarkReportMetric>; readonly "rights_basis": string; readonly "schema_version": "org.searchright.benchmark-report.v1"; };

export type BibliographicRecord = { readonly "abstract_text": string | null; readonly "authors": ReadonlyArray<string>; readonly "container_title": string | null; readonly "identifiers": { readonly "doi"?: string | null; readonly "isbn"?: string | null; readonly "openalex"?: string | null; readonly "other"?: { readonly [key: string]: string; }; readonly "pmcid"?: string | null; readonly "pmid"?: string | null; readonly "trial_registration"?: string | null; }; readonly "kind": "journal_article" | "preprint" | "conference" | "trial_registry" | "thesis" | "report" | "dataset" | { readonly "other": string; }; readonly "languages": ReadonlyArray<string>; readonly "native_id": string; readonly "provider_metadata": JsonValue; readonly "publication_date": string | null; readonly "publication_year": number | null; readonly "record_id": string; readonly "schema_version": "org.searchright.bibliographic-record.v1"; readonly "source_receipt_id": string; readonly "subjects": ReadonlyArray<string>; readonly "title": string; readonly "urls": ReadonlyArray<string>; };

export type CompiledStrategy = { readonly "compilation_hash": string; readonly "compiler_version": string; readonly "dialect": "pub_med" | "ovid_medline" | "embase" | "europe_pmc" | "cinahl_ebsco" | "psyc_info_ovid" | "scopus" | "web_of_science" | "crossref" | "open_alex" | "clinical_trials_gov" | "generic_boolean" | { readonly "custom": string; }; readonly "fidelity": "exact" | "source_equivalent" | "approximate" | "degraded"; readonly "loss_codes": ReadonlyArray<string>; readonly "query": string; readonly "review_required": boolean; readonly "schema_version": "org.searchright.compiled-strategy.v1"; readonly "strategy_id": string; readonly "warnings": ReadonlyArray<{ readonly "code": string; readonly "message": string; readonly "review_required": boolean; }>; };

export type ComponentHealth = { readonly "component": string; readonly "diagnostics": ReadonlyArray<string>; readonly "observed_at": string; readonly "ready": boolean; readonly "schema_version": "org.searchright.component-health.v1"; readonly "state": "healthy" | "degraded" | "unhealthy" | "disabled"; };

export type ConsumerContractSuiteInteraction = { readonly "automatic_promotion": false; readonly "consumer": string; readonly "consumer_contracts": ConsumerContractSuiteNonemptyStrings; readonly "consumer_gates": ConsumerContractSuiteNonemptyStrings; readonly "contract_version": string; readonly "failure_semantics": string; readonly "fixture_paths": ConsumerContractSuiteNonemptyStrings; readonly "id": string; readonly "integration_id": string; readonly "producer": string; readonly "producer_contracts": ConsumerContractSuiteNonemptyStrings; readonly "producer_gates": ConsumerContractSuiteNonemptyStrings; readonly "status": "prepared_not_executed" | "fixture_verified" | "downstream_verified" | "suspended"; };

export type ConsumerContractSuiteNonemptyStrings = ReadonlyArray<string>;

export type ConsumerContractSuite = { readonly "claim_boundary": string; readonly "generated_at": string; readonly "interactions": ReadonlyArray<ConsumerContractSuiteInteraction>; readonly "schema_version": "org.searchright.consumer-contract-suite.v1"; };

export type DataHandlingDecision = { readonly "blockers": ReadonlyArray<string>; readonly "human_approval_required": boolean; readonly "permitted": boolean; readonly "policy_id": string; readonly "request_id": string; readonly "schema_version": "org.searchright.data-handling-decision.v1"; readonly "warnings": ReadonlyArray<string>; };

export type DataHandlingRequest = { readonly "classification": "public_metadata" | "internal_review_data" | "confidential" | "restricted_full_text" | "sensitive_personal_data"; readonly "cross_border_transfer": boolean; readonly "deployment_mode": "local_only" | "institution_self_hosted" | "hosted_single_tenant" | "hosted_multi_tenant"; readonly "dry_run": boolean; readonly "operation": "metadata" | "full_text_analysis" | "full_text_persistence" | "export" | "telemetry" | "external_model_processing"; readonly "region": string | null; readonly "request_id": string; readonly "retention_days": number; readonly "review_id": string; readonly "schema_version": "org.searchright.data-handling-request.v1"; };

export type DataLifecycleDecision = { readonly "blockers": ReadonlyArray<string>; readonly "effects_authorized": boolean; readonly "immutable_audit_preserved": true; readonly "permitted": boolean; readonly "policy_id": string; readonly "receipt_required": boolean; readonly "request_id": string; readonly "schema_version": "org.searchright.data-lifecycle-decision.v1"; readonly "tombstone_target_ids": ReadonlyArray<string>; readonly "warnings": ReadonlyArray<string>; };

export type DataLifecycleRequest = { readonly "action": "retain" | "export" | "delete"; readonly "approval": null | { readonly "action": "retain" | "export" | "delete"; readonly "approval_id": string; readonly "approved_at": string; readonly "approved_by": string; readonly "expires_at": string; readonly "nonce": string; readonly "policy_id": string; readonly "request_digest": string; readonly "review_id": string; }; readonly "classification": "public_metadata" | "internal_review_data" | "confidential" | "restricted_full_text" | "sensitive_personal_data"; readonly "execution_mode": "preview" | "apply"; readonly "export_destination": string | null; readonly "includes_audit_log": boolean; readonly "legal_hold": boolean; readonly "request_id": string; readonly "retention_days": number | null; readonly "review_id": string; readonly "schema_version": "org.searchright.data-lifecycle-request.v1"; readonly "target_ids": ReadonlyArray<string>; };

export type Diagnostic = { readonly "blocking": boolean; readonly "code": string; readonly "column": number | null; readonly "evidence_ids": ReadonlyArray<string>; readonly "line": number | null; readonly "locale": "en_au" | "en_nz" | "en_us" | "mi_nz" | { readonly "custom": string; }; readonly "message": string; readonly "path": string | null; readonly "remediation": string | null; readonly "schema_version": "org.searchright.diagnostic.v1"; readonly "severity": "information" | "warning" | "error" | "blocking"; };

export type DiscoveryRun = { readonly "edges": ReadonlyArray<{ readonly "discovered_id": string; readonly "edge_id": string; readonly "method": "backward_citation" | "forward_citation" | "similar_articles" | "trial_registry" | "repository" | "grey_literature" | "handsearch" | "contact" | { readonly "other": string; }; readonly "provider_id": string; readonly "receipt_id": string; readonly "seed_id": string; }>; readonly "maximum_depth": number; readonly "maximum_records": number; readonly "method": "backward_citation" | "forward_citation" | "similar_articles" | "trial_registry" | "repository" | "grey_literature" | "handsearch" | "contact" | { readonly "other": string; }; readonly "requires_human_release": boolean; readonly "review_id": string; readonly "run_id": string; readonly "schema_version": "org.searchright.discovery-run.v1"; readonly "seed_ids": ReadonlyArray<string>; };

export type DocumentEvidenceCallout = { readonly "callout_id": string; readonly "confidence": number | null; readonly "reference_id": string | null; readonly "review_required": boolean; readonly "span": DocumentEvidenceSpan; readonly "surface": string; };

export type DocumentEvidenceDiagnostic = { readonly "code": string; readonly "message": string; readonly "severity": "info" | "warning" | "error"; readonly "subject_id": string | null; };

export type DocumentEvidenceField = { readonly "field": string; readonly "span": DocumentEvidenceSpan | null; readonly "value": string; };

export type DocumentEvidenceProvenance = { readonly "backend": string; readonly "backend_version": string | null; readonly "configuration": string; readonly "endpoint_class": string | null; readonly "input_sha256": string | null; readonly "route_trace_digest": string | null; };

export type DocumentEvidenceReference = { readonly "confidence": number | null; readonly "fields": ReadonlyArray<DocumentEvidenceField>; readonly "raw_citation": string; readonly "reference_id": string; readonly "review_required": boolean; readonly "span": DocumentEvidenceSpan | null; };

export type DocumentEvidenceSpan = { readonly "bounding_box": ReadonlyArray<number>; readonly "end_byte": number | null; readonly "page": number | null; readonly "source_id": string | null; readonly "start_byte": number | null; readonly "surface": string; };

export type DocumentEvidence = { readonly "canonical_write_permitted": false; readonly "citation_callouts": ReadonlyArray<DocumentEvidenceCallout>; readonly "diagnostics": ReadonlyArray<DocumentEvidenceDiagnostic>; readonly "document_id": string; readonly "provenance": DocumentEvidenceProvenance; readonly "references": ReadonlyArray<DocumentEvidenceReference>; readonly "retained_full_text": boolean; readonly "schema_version": "org.searchright.document-evidence.v1"; readonly "upstream_schema_version": string; };

export type EvidenceDebt = { readonly "assertions": { readonly "by_mapping_confidence": { readonly [key: string]: number; }; readonly "by_state": { readonly [key: string]: number; }; readonly "open_gate_entries": number; readonly "total": number; readonly "track_level_only": number; readonly "without_symbol_mapping": number; }; readonly "claim_boundary": string; readonly "evidence_ceiling": "source_verified"; readonly "maturity": { readonly "critical_blockers": ReadonlyArray<string>; readonly "decision": string; }; readonly "priority_queue": ReadonlyArray<{ readonly "closure_evidence": ReadonlyArray<string>; readonly "debt": string; readonly "priority": number; readonly "reason": string; }>; readonly "provider_policy": { readonly "providers": number; readonly "reviewed_with_evidence": number; }; readonly "publication": { readonly "candidate_packages": number; readonly "publish_ready": number; }; readonly "schema_version": "org.searchright.evidence-debt.v1"; readonly "static_gates": { readonly "catalogued": number; readonly "harness": number; readonly "unregistered_assertion_commands": ReadonlyArray<string>; }; readonly "tracks": { readonly "by_state": { readonly [key: string]: number; }; readonly "total": number; }; };

export type ExecutionEnvelope = { readonly "allowed_hosts": ReadonlyArray<string>; readonly "approved_by": string | null; readonly "dry_run": boolean; readonly "full_text_handling": "metadata_only" | "local_rights_compliant" | "minimal_evidence_excerpt"; readonly "maximum_records": number; readonly "maximum_seconds": number; readonly "network": "disabled" | "allowlisted_https" | "licensed_allowlist"; readonly "operation_id": string; readonly "review_id": string; readonly "schema_version": "org.searchright.execution-envelope.v1"; readonly "secret_handling": "none" | "environment_redacted" | "host_managed_reference"; readonly "untrusted_content": "data_only" | "sanitise_then_data_only" | "human_inspection_required"; };

export type GateCatalog = { readonly "default_capabilities": { readonly "compiler_required": false; readonly "external_writes": false; readonly "network": false; }; readonly "gates": ReadonlyArray<{ readonly "category": string; readonly "claim_boundary": string; readonly "command": string; readonly "compiler_required": false; readonly "covered_assertions": ReadonlyArray<string>; readonly "evidence_ceiling": "source_verified" | "source_reproducible"; readonly "external_writes": false; readonly "gate_id": string; readonly "harness_gate": boolean; readonly "network": false; readonly "script": string; }>; readonly "generated_from": ReadonlyArray<string>; readonly "schema_version": "org.searchright.gate-catalog.v1"; };

export type GithubControlPlaneApplySummaryArtifact = { readonly "digest": string; readonly "expires_at": string; readonly "files": ReadonlyArray<{ readonly "name": string; readonly "sha256": string; }>; readonly "id": number; readonly "name": string; };

export type GithubControlPlaneApplySummaryAudit = { readonly "canonical_issues_observed": GithubControlPlaneApplySummaryNonnegativeCount; readonly "canonical_project_items_observed": GithubControlPlaneApplySummaryNonnegativeCount; readonly "content_drift": 0; readonly "label_drift": 0; readonly "mutation_operations": 0; readonly "noncanonical_project_items_observed": GithubControlPlaneApplySummaryNonnegativeCount; readonly "recognised_value_mismatches": 0; readonly "relationships_observed": GithubControlPlaneApplySummaryNonnegativeCount; readonly "status": "passed"; readonly "task_state_drift": 0; readonly "unrecognised_value_shapes": 0; };

export type GithubControlPlaneApplySummaryIssueSync = { readonly "canonical_issues": GithubControlPlaneApplySummaryNonnegativeCount; readonly "delete_operations": 0; readonly "issues_unchanged": GithubControlPlaneApplySummaryNonnegativeCount; readonly "mode": "apply"; readonly "relationships_existing": GithubControlPlaneApplySummaryNonnegativeCount; readonly "remaining_after_run": 0; readonly "task_states_unchanged": GithubControlPlaneApplySummaryNonnegativeCount; };

export type GithubControlPlaneApplySummaryNonnegativeCount = number;

export type GithubControlPlaneApplySummaryProjectSync = { readonly "canonical_items": GithubControlPlaneApplySummaryNonnegativeCount; readonly "delete_operations": 0; readonly "existing_items": GithubControlPlaneApplySummaryNonnegativeCount; readonly "field_updates": GithubControlPlaneApplySummaryNonnegativeCount; readonly "known_equal_field_values": GithubControlPlaneApplySummaryNonnegativeCount; readonly "mode": "apply"; readonly "project_id": string; readonly "project_number": number; readonly "project_url": string; readonly "remaining_after_run": 0; };

export type GithubControlPlaneApplySummaryWorkflowRun = { readonly "credential_check": "passed"; readonly "environment": "github-project-write"; readonly "event": "workflow_dispatch"; readonly "id": number; readonly "url": string; };

export type GithubControlPlaneApplySummary = { readonly "artifact": GithubControlPlaneApplySummaryArtifact; readonly "audit": GithubControlPlaneApplySummaryAudit; readonly "claim_boundary": string; readonly "issue_sync": GithubControlPlaneApplySummaryIssueSync; readonly "project_sync": GithubControlPlaneApplySummaryProjectSync; readonly "repository": string; readonly "schema_version": "org.searchright.github-control-plane-apply-summary.v1"; readonly "source_revision": string; readonly "status": "passed"; readonly "workflow_run": GithubControlPlaneApplySummaryWorkflowRun; };

export type GithubIssueHierarchy = { readonly "apply_permitted": false; readonly "epic_key": string; readonly "generated_at": string; readonly "nodes": ReadonlyArray<{ readonly "body_path": string; readonly "key": string; readonly "kind": "epic" | "track" | "phase"; readonly "labels": ReadonlyArray<string>; readonly "parent_key": string | null; readonly "status": string; readonly "title": string; }>; readonly "repository": string; readonly "schema_version": "org.searchright.github-issue-hierarchy.v1"; };

export type GithubIssueHierarchyV2 = { readonly "apply_permitted": false; readonly "epic_key": string; readonly "generated_at": string; readonly "nodes": ReadonlyArray<{ readonly "body_path": string; readonly "desired_state": "open" | "closed"; readonly "key": string; readonly "kind": "epic" | "track" | "phase" | "task"; readonly "labels": ReadonlyArray<string>; readonly "parent_key": string | null; readonly "phase_number": number | null; readonly "project_fields": { readonly [key: string]: string | number; }; readonly "status": "prepared_not_synced"; readonly "task_number": number | null; readonly "title": string; readonly "track_id": string | null; }>; readonly "project_manifest": "conductor/github/project.json"; readonly "repository": string; readonly "schema_version": "org.searchright.github-issue-hierarchy.v2"; readonly "state_sync_policy": "task_issues_only"; };

export type GithubProject = { readonly "apply_permitted": false; readonly "fields": ReadonlyArray<{ readonly "data_type": "SINGLE_SELECT" | "TEXT" | "NUMBER" | "DATE"; readonly "name": string; readonly "options"?: ReadonlyArray<string>; }>; readonly "link_repository": boolean; readonly "owner": string; readonly "owner_type": "user" | "organization"; readonly "project_number": null; readonly "readme_path": string; readonly "repository": string; readonly "schema_version": "org.searchright.github-project.v1"; readonly "short_description": string; readonly "sync": { readonly "archive_policy": "never_automatic"; readonly "checkpoint_policy": "ignored_atomic_resumable"; readonly "delete_policy": "never"; readonly "field_policy": "manifest_owned_custom_fields_only"; readonly "hierarchy_path": string; readonly "identity_field": string; readonly "labels_path": string; readonly "minimum_interval_ms": number; readonly "partial_run_policy": "canonical_order_resume_after"; readonly "promotion_policy": "remote_state_cannot_promote_evidence"; readonly "receipt_directory": ".searchright/receipts"; readonly "remote_audit_path": "scripts/audit_github_control_plane.py"; readonly "state_policy": "task_issues_only"; }; readonly "title": string; readonly "views": ReadonlyArray<{ readonly "filter": string; readonly "layout": "BOARD_LAYOUT" | "ROADMAP_LAYOUT" | "TABLE_LAYOUT"; readonly "name": string; }>; readonly "visibility": "public" | "private"; };

export type GithubRepositorySettings = { readonly "apply_permitted": false; readonly "claim_boundary": string; readonly "description": string; readonly "environments": ReadonlyArray<string>; readonly "features": { readonly "discussions": boolean; readonly "issues": boolean; readonly "projects": boolean; readonly "wiki": boolean; }; readonly "homepage": string; readonly "merge_policy": { readonly "allow_auto_merge": boolean; readonly "allow_update_branch": boolean; readonly "delete_head_branch": boolean; readonly "merge_commit": boolean; readonly "rebase": boolean; readonly "squash": boolean; }; readonly "repository": string; readonly "ruleset": { readonly "deletion": false; readonly "enforcement": "active" | "evaluate" | "disabled"; readonly "include": ReadonlyArray<string>; readonly "name": string; readonly "non_fast_forward": false; readonly "required_linear_history": boolean; readonly "required_signed_commits": boolean; readonly "required_status_checks": ReadonlyArray<string>; readonly "target": "branch"; }; readonly "schema_version": "org.searchright.github-repository-settings.v1"; readonly "security": { readonly "automated_security_fixes": boolean; readonly "private_vulnerability_reporting": boolean; readonly "push_protection": boolean; readonly "secret_scanning": boolean; readonly "vulnerability_alerts": boolean; }; readonly "topics": ReadonlyArray<string>; readonly "visibility": "public" | "private"; };

export type IncidentRecord = { readonly "components": ReadonlyArray<string>; readonly "containment": ReadonlyArray<string>; readonly "data_exposure_suspected": boolean; readonly "detected_at": string; readonly "impact": string; readonly "incident_id": string; readonly "postmortem_required": boolean; readonly "schema_version": "org.searchright.incident-record.v1"; readonly "severity": "informational" | "low" | "medium" | "high" | "critical"; readonly "status": string; };

export type InstitutionalPolicy = { readonly "allowed_classifications": ReadonlyArray<"public_metadata" | "internal_review_data" | "confidential" | "restricted_full_text" | "sensitive_personal_data">; readonly "approved_by": string; readonly "cross_border_transfer_allowed": boolean; readonly "deployment_modes": ReadonlyArray<"local_only" | "institution_self_hosted" | "hosted_single_tenant" | "hosted_multi_tenant">; readonly "effective_from": string; readonly "external_model_processing_allowed": boolean; readonly "full_text_persistence_allowed": boolean; readonly "institution": string; readonly "maximum_retention_days": number; readonly "permitted_regions": ReadonlyArray<string>; readonly "policy_id": string; readonly "review_by": string | null; readonly "schema_version": "org.searchright.institutional-policy.v1"; readonly "telemetry_allowed": boolean; };

export type IntegrationPassportContracts = ReadonlyArray<{ readonly "name": string; readonly "path": string; readonly "required": boolean; readonly "version": string; }>;

export type IntegrationPassport = { readonly "inputs"?: JsonValue; } | { readonly "outputs"?: JsonValue; };

export type IntegrationReleaseTrain = { readonly "automatic_promotion": false; readonly "claim_boundary": string; readonly "components": ReadonlyArray<{ readonly "consumer_contract": string | null; readonly "passport": string | null; readonly "promotion_order": number; readonly "repository": string; readonly "role": string; }>; readonly "contract_surface": string; readonly "ecosystem_lock": string; readonly "generated_at": string; readonly "public_package_policy": string; readonly "release_train_id": string; readonly "rollback": ReadonlyArray<string>; readonly "schema_version": "org.searchright.integration-release-train.v1"; readonly "stages": ReadonlyArray<{ readonly "automatic": false; readonly "id": string; readonly "required_evidence": string; }>; };

export type InterchangeReceipt = { readonly "input_digest": string; readonly "input_format": "searchright_json" | "json_lines" | "csl_json" | "ris" | "nbib" | "bibtex" | "endnote_xml" | "csv" | "parquet" | { readonly "custom": string; }; readonly "lossless": boolean; readonly "operation_id": string; readonly "output_digest": string; readonly "output_format": "searchright_json" | "json_lines" | "csl_json" | "ris" | "nbib" | "bibtex" | "endnote_xml" | "csv" | "parquet" | { readonly "custom": string; }; readonly "records_read": number; readonly "records_written": number; readonly "review_id": string; readonly "schema_version": "org.searchright.interchange-receipt.v1"; readonly "warnings": ReadonlyArray<string>; };

export type LicensedAdapter = { readonly "allowed_hosts": ReadonlyArray<string>; readonly "credential_environment_variable": string; readonly "database": string; readonly "dialect": "embase" | "scopus" | "web_of_science" | "ovid_medline" | "psyc_info_ovid"; readonly "export_formats": ReadonlyArray<string>; readonly "live_opt_in_environment_variable": string; readonly "persist_raw_responses": false; readonly "platform": string; readonly "provider_id": string; readonly "schema_version": "org.searchright.licensed-adapter.v1"; readonly "terms_review": string; };

export type LivingUpdate = { readonly "changes": ReadonlyArray<{ readonly "after_digest": string | null; readonly "before_digest": string | null; readonly "kind": "added" | "updated" | "missing_from_source" | "merged" | "restored"; readonly "note": string; readonly "record_id": string; }>; readonly "completed_at": string | null; readonly "cursors_after": ReadonlyArray<{ readonly "cursor_kind": string; readonly "provider_id": string; readonly "retrieved_through": string | null; readonly "value": string; }>; readonly "cursors_before": ReadonlyArray<{ readonly "cursor_kind": string; readonly "provider_id": string; readonly "retrieved_through": string | null; readonly "value": string; }>; readonly "parent_run_id": string | null; readonly "protocol_version": string; readonly "requires_human_release": boolean; readonly "review_id": string; readonly "run_id": string; readonly "schema_version": "org.searchright.living-update.v1"; readonly "started_at": string; readonly "status": "planned" | "running" | "completed" | "failed" | "cancelled"; readonly "supersedes_run_id": string | null; };

export type NamedFilterPackApplicability = { readonly "intended_use": string; readonly "limitations": ReadonlyArray<string>; readonly "platform_versions": ReadonlyArray<string>; readonly "source_ids": ReadonlyArray<string>; };

export type NamedFilterPackChecksum = { readonly "algorithm": "sha256"; readonly "digest": string; };

export type NamedFilterPackDate = string;

export type NamedFilterPackDialect = "pub_med" | "ovid_medline" | "embase" | "europe_pmc" | "cinahl_ebsco" | "psyc_info_ovid" | "scopus" | "web_of_science" | "crossref" | "open_alex" | "clinical_trials_gov" | "generic_boolean" | { readonly "custom": string; };

export type NamedFilterPackNamedFilter = { readonly "applicability": NamedFilterPackApplicability; readonly "checksum": NamedFilterPackChecksum; readonly "dialect": NamedFilterPackDialect; readonly "effective_from": NamedFilterPackDate; readonly "expires_on": NamedFilterPackDate; readonly "expression": string; readonly "filter_id": string; readonly "name": string; readonly "rights": NamedFilterPackRights; readonly "source": NamedFilterPackSource; readonly "validation": NamedFilterPackValidation; readonly "version": string; };

export type NamedFilterPackRights = { readonly "basis": string; readonly "decided_by": string; readonly "evidence_reference": string; readonly "redistribution": "permitted" | "prohibited" | "review_required"; };

export type NamedFilterPackSource = { readonly "citation": string; readonly "source_uri": null | string; readonly "source_version": string; readonly "title": string; };

export type NamedFilterPackValidation = { readonly "evidence_reference": string; readonly "evidence_sha256": string; readonly "method": string; readonly "reviewer_id": string; readonly "reviewer_role": string; readonly "state": "structural_only" | "methodologically_reviewed" | "methodologically_reviewed_and_provider_current"; };

export type NamedFilterPack = { readonly "expires_on": NamedFilterPackDate; readonly "filters": ReadonlyArray<NamedFilterPackNamedFilter>; readonly "pack_id": string; readonly "schema_version": "org.searchright.named-filter-pack.v1"; readonly "title": string; readonly "validated_on": NamedFilterPackDate; readonly "version": string; };

export type NativeSearchStrategySpan = { readonly "end_byte": number; readonly "start_byte": number; };

export type NativeSearchStrategy = { readonly "diagnostics": ReadonlyArray<{ readonly "code": string; readonly "message": string; readonly "review_required": boolean; readonly "severity": "info" | "warning" | "error"; readonly "span": null | NativeSearchStrategySpan; }>; readonly "dialect": "pub_med" | "ovid_medline" | "embase" | "europe_pmc" | "cinahl_ebsco" | "psyc_info_ovid" | "scopus" | "web_of_science" | "crossref" | "open_alex" | "clinical_trials_gov" | "generic_boolean" | { readonly "custom": string; }; readonly "lines": ReadonlyArray<{ readonly "kind": "expression" | "set_combination" | "limit" | "comment" | "blank" | "unknown"; readonly "line_id": string; readonly "native_set_id": string | null; readonly "span": NativeSearchStrategySpan; readonly "text": string; }>; readonly "normalisation_state": "raw_only" | "partial" | "complete"; readonly "parser_version": string; readonly "raw_text": string; readonly "schema_version": "org.searchright.native-search-strategy.v1"; readonly "semantic_strategy": null | SearchStrategy; readonly "strategy_id": string; };

export type PrismaFlow = { readonly "automation_removed": number; readonly "duplicates_removed": number; readonly "full_text_exclusions": ReadonlyArray<{ readonly "count": number; readonly "label": string; readonly "reason_id": string; }>; readonly "other_removed": number; readonly "records_databases": number; readonly "records_excluded": number; readonly "records_other": number; readonly "records_registers": number; readonly "records_screened": number; readonly "reports_assessed": number; readonly "reports_included": number; readonly "reports_not_retrieved": number; readonly "reports_sought": number; readonly "review_id": string; readonly "schema_version": "org.searchright.prisma-flow.v1"; readonly "studies_included": number; };

export type ProtocolAmendment = { readonly "amendment_id": string; readonly "changes": ReadonlyArray<{ readonly "after": string; readonly "before": string | null; readonly "path": string; readonly "rationale": string; }>; readonly "decided_at": string | null; readonly "decided_by": string | null; readonly "decision": "proposed" | "approved" | "rejected" | "withdrawn"; readonly "kind": "scope" | "eligibility" | "information_sources" | "search_strategy" | "screening" | "analysis" | "governance" | { readonly "other": string; }; readonly "proposed_at": string; readonly "proposed_by": string; readonly "requires_reprocessing": boolean; readonly "retrospective_impact": string; readonly "review_id": string; readonly "schema_version": "org.searchright.protocol-amendment.v1"; readonly "version_after": string; readonly "version_before": string; };

export type ProviderComponent = { readonly "abi_version": string; readonly "allowed_hosts": ReadonlyArray<string>; readonly "authority_rationale": ReadonlyArray<string>; readonly "capabilities": ReadonlyArray<"search" | "metadata_read" | "input_file_read" | "workspace_write" | "network_read" | "telemetry">; readonly "component_digest": string; readonly "component_id": string; readonly "component_version": string; readonly "fixture_mode": boolean; readonly "max_fuel": number; readonly "max_memory_mib": number; readonly "schema_version": "org.searchright.provider-component.v1"; };

export type ProviderComponentReleaseSignature = { readonly "algorithm": "ed25519"; readonly "component_digest": string; readonly "component_id": string; readonly "component_version": string; readonly "expires_at": string; readonly "key_id": string; readonly "manifest_digest": string; readonly "schema_version": "org.searchright.provider-component-release-signature.v1"; readonly "signature": string; readonly "signed_at": string; readonly "trust_policy_id": string; };

export type ProviderComponentTrustPolicy = { readonly "policy_id": string; readonly "revocations": ReadonlyArray<{ readonly "evidence_reference": string; readonly "key_id": string; readonly "revoked_at": string; }>; readonly "schema_version": "org.searchright.provider-component-trust-policy.v1"; readonly "trusted_keys": ReadonlyArray<{ readonly "algorithm": "ed25519"; readonly "component_ids": ReadonlyArray<string>; readonly "key_id": string; readonly "public_key": string; readonly "valid_from": string; readonly "valid_until": string; }>; };

export type ProviderManifest = { readonly "allowed_hosts": ReadonlyArray<string>; readonly "authentication_required": boolean; readonly "capabilities": ReadonlyArray<"search" | "pagination" | "import" | "lookup" | "backward_citation" | "forward_citation" | "updates">; readonly "default_min_interval_ms": number; readonly "display_name": string; readonly "licensed": boolean; readonly "policy_notes": ReadonlyArray<string>; readonly "provider_id": string; readonly "support_level": "planned" | "fixture_backed" | "opt_in_live" | "maintained"; readonly "version": string; };

export type ProviderPage = { readonly "diagnostics": { readonly [key: string]: JsonValue; }; readonly "next_cursor": string | null; readonly "records": ReadonlyArray<BibliographicRecord>; readonly "schema_version": "org.searchright.provider-page.v1"; readonly "total_available": number | null; };

export type ProviderPolicySet = { readonly "automatic_approval": false; readonly "claim_boundary": string; readonly "providers": ReadonlyArray<{ readonly "access_class": string; readonly "contact_identity_required": boolean; readonly "credential_environment_variables": ReadonlyArray<string>; readonly "credential_receipt_policy": "never_persist" | "contact_value_redacted" | "not_applicable"; readonly "documentation_url": string; readonly "endpoint": string; readonly "live_canary_requires_opt_in": true; readonly "manual_review_required_before_live_release": true; readonly "minimum_interval_ms_with_key": number | null; readonly "minimum_interval_ms_without_key": number; readonly "notes": ReadonlyArray<string>; readonly "policy_review_status": "source_identified_not_legally_approved" | "reviewed_with_evidence" | "blocked"; readonly "privacy_url": string; readonly "provider_id": string; readonly "query_classification": "public_metadata" | "internal_review_data" | "confidential"; readonly "raw_response_retention": "disabled_by_default"; readonly "redistribution_policy": string; readonly "response_classification": "public_metadata"; readonly "review_due": string; readonly "review_evidence": ReadonlyArray<string>; readonly "source_checked_at": string; readonly "terms_or_usage_url": string; }>; readonly "schema_version": "org.searchright.provider-policy-set.v1"; readonly "source_epoch": string; };

export type QueryAstField = "all" | "title" | "abstract" | "title_abstract" | "author" | "journal" | "identifier" | "subject_heading" | "keyword" | { readonly "custom": string; };

export type QueryAstQuery = { readonly "op": "term"; readonly "term": QueryAstTerm; } | { readonly "children": ReadonlyArray<QueryAstQuery>; readonly "op": "and" | "or"; } | { readonly "exclude": QueryAstQuery; readonly "include": QueryAstQuery; readonly "op": "not"; } | { readonly "distance": number; readonly "left": QueryAstQuery; readonly "op": "proximity"; readonly "ordered": boolean; readonly "right": QueryAstQuery; };

export type QueryAstTerm = { readonly "explode": boolean; readonly "fields": ReadonlyArray<QueryAstField>; readonly "phrase": boolean; readonly "text": string; readonly "truncation": boolean; readonly "vocabulary": null | string; };

export type QueryAst = QueryAstQuery;

export type RankingCalibration = { readonly "approved_by": string | null; readonly "approved_for_prioritisation": boolean; readonly "auto_exclusion_prohibited": true; readonly "counts": { readonly "false_negative": number; readonly "false_positive": number; readonly "true_negative": number; readonly "true_positive": number; }; readonly "minimum_sensitivity": number; readonly "ranker_version": string; readonly "review_id": string; readonly "schema_version": "org.searchright.ranking-calibration.v1"; readonly "threshold": number; };

export type RecoveryRehearsal = { readonly "atomic_replace_checked": boolean; readonly "claim_boundary": string; readonly "errors": ReadonlyArray<string>; readonly "files": number; readonly "restore_idempotency_checked": boolean; readonly "scenario_id": string; readonly "schema_version": "org.searchright.recovery-rehearsal.v1"; readonly "stale_temporary_checked": boolean; readonly "status": "passed" | "failed"; readonly "tamper_detection_checked": boolean; };

export type RedactionProfile = { readonly "claim_boundary": string; readonly "minimum_high_entropy_length": number; readonly "preserve_key_names": true; readonly "profile_id": string; readonly "redact_bearer_tokens": true; readonly "redact_email_addresses": true; readonly "redact_probable_high_entropy_values": true; readonly "replacement": "[REDACTED]"; readonly "safe_query_keys": ReadonlyArray<string>; readonly "schema_version": "org.searchright.redaction-profile.v1"; readonly "sensitive_object_keys": ReadonlyArray<string>; readonly "sensitive_query_keys": ReadonlyArray<string>; };

export type ReleaseRehearsal = { readonly "automatic_registry_submission": false; readonly "automatic_release": false; readonly "claim_boundary": string; readonly "pilot_profiles": ReadonlyArray<string>; readonly "required_gates": ReadonlyArray<string>; readonly "rollback_required": true; readonly "schema_version": "org.searchright.release-rehearsal.v1"; readonly "source_epoch": string; readonly "status": "prepared_not_executed" | "in_progress" | "failed" | "passed"; readonly "target": string; };

export type ResearchObjectHandoffPlan = { readonly "claim_boundary": string; readonly "delegated_export_track": "25"; readonly "deposit_authorized": false; readonly "execution_mode": "dry_run"; readonly "input_artifacts": ReadonlyArray<{ readonly "artifact_id": string; readonly "kind": "srpack" | "audit_export" | "source_receipts"; readonly "sha256": string; }>; readonly "osf_acceptance_claimed": false; readonly "plan_id": string; readonly "prerequisites": ReadonlyArray<string>; readonly "proposed_destinations": ReadonlyArray<{ readonly "external_write": true; readonly "kind": "ro_crate" | "osf"; readonly "target_reference": string; }>; readonly "review_id": string; readonly "ro_crate_conformance_claimed": false; readonly "schema_version": "org.searchright.research-object-handoff-plan.v1"; };

export type ReviewBundleManifest = { readonly "bundle_id": string; readonly "claim_boundary": string; readonly "descriptor_merkle_root": string; readonly "entries": ReadonlyArray<{ readonly "archive_path": string; readonly "media_type": string; readonly "path": string; readonly "role": string; readonly "sha256": string; readonly "size": number; }>; readonly "entry_count": number; readonly "format_version": "1"; readonly "payload_bytes": number; readonly "policy": { readonly "deterministic": true; readonly "external_writes_allowed": false; readonly "max_file_bytes": number; readonly "max_files": number; readonly "max_total_bytes": number; readonly "network_required": false; readonly "secret_scan_required": true; readonly "symlinks_allowed": false; }; readonly "review_id": string; readonly "schema_version": "org.searchright.review-bundle-manifest.v1"; readonly "source_epoch": string; };

export type ReviewPlanCriterion = { readonly "domain": string; readonly "id": string; readonly "priority": number; readonly "rationale": string; readonly "rule": string; readonly "stage": "title_abstract" | "full_text" | "any"; };

export type ReviewPlanEligibility = { readonly "exclude": ReadonlyArray<ReviewPlanCriterion>; readonly "include": ReadonlyArray<ReviewPlanCriterion>; readonly "version": string; };

export type ReviewPlanFrameworkKind = "pico" | "pecos" | "pcc" | "spider" | "peo" | { readonly "custom": string; };

export type ReviewPlanGovernance = { readonly "conflict_resolution": string; readonly "full_text_reviewers": number; readonly "press_review_required": boolean; readonly "protocol_amendment_roles": ReadonlyArray<string>; readonly "title_abstract_reviewers": number; };

export type ReviewPlanProtocol = { readonly "identifier"?: null; readonly "registry"?: null; } | { readonly "identifier"?: string; readonly "registry"?: string; };

export type ReviewPlanQuestion = { readonly "framework": { readonly "elements": { readonly [key: string]: string; }; readonly "kind": ReviewPlanFrameworkKind; }; readonly "notes"?: ReadonlyArray<string>; readonly "text": string; };

export type ReviewPlanReviewKind = "systematic" | "scoping" | "rapid" | "living" | "evidence_map" | "umbrella" | { readonly "other": string; };

export type ReviewPlanSource = { readonly "access_notes": ReadonlyArray<string>; readonly "id": string; readonly "kind": ReviewPlanSourceKind; readonly "name": string; readonly "platform": null | string; readonly "provider": string; readonly "required": boolean; };

export type ReviewPlanSourceKind = "database" | "register" | "repository" | "website" | "citation_search" | "contact" | "handsearch" | "grey_literature" | "import" | { readonly "other": string; };

export type ReviewPlan = { readonly "eligibility": ReviewPlanEligibility; readonly "governance": ReviewPlanGovernance; readonly "information_sources": ReadonlyArray<ReviewPlanSource>; readonly "objectives": ReadonlyArray<string>; readonly "protocol": ReviewPlanProtocol; readonly "question": ReviewPlanQuestion; readonly "review_id": string; readonly "review_kind": ReviewPlanReviewKind; readonly "schema_version": "org.searchright.review-plan.v1"; readonly "strategy_ids": ReadonlyArray<string>; readonly "title": string; };

export type ReviewStateSnapshot = { readonly "claim_boundary": string; readonly "event_type_counts": { readonly [key: string]: number; }; readonly "last_event_id": string; readonly "plan_validated": boolean; readonly "protocol_amendments": ReadonlyArray<string>; readonly "review_id": string; readonly "schema_version": "org.searchright.review-state-snapshot.v1"; readonly "screening": { readonly "advisory_recommendation_count": number; readonly "final_decision_counts": { readonly [key: string]: number; }; readonly "final_decisions": ReadonlyArray<{ readonly "decision": string | null; readonly "event_id": string; readonly "record_id": string; readonly "reviewer_id": string | null; readonly "stage": string | null; }>; readonly "rejected_final_authority_event_ids": ReadonlyArray<string>; }; readonly "search_runs": ReadonlyArray<{ readonly "event_id": string; readonly "record_count": number | null; readonly "run_id": string; readonly "source_id": string | null; }>; readonly "source_event_count": number; readonly "source_head_hash": string; readonly "state_sha256": string; readonly "state_version": 1; readonly "status": string; readonly "unknown_event_types": ReadonlyArray<string>; };

export type SchemaMigrationPlan = { readonly "automatic_apply": false; readonly "backup_required": true; readonly "claim_boundary": string; readonly "classification": string; readonly "destructive": false; readonly "family": string; readonly "from_version": number; readonly "migration_id": string; readonly "preconditions": ReadonlyArray<string>; readonly "rollback": { readonly "losses": ReadonlyArray<string>; readonly "strategy": string; readonly "supported": true; }; readonly "schema_version": "org.searchright.schema-migration-plan.v1"; readonly "to_version": number; readonly "transformations": ReadonlyArray<{ readonly "description": string; readonly "operation": "preserve" | "derive" | "rename" | "transform"; readonly "path": string; }>; readonly "verification": ReadonlyArray<string>; };

export type SchemaMigrationRegistry = { readonly "automatic_migration": false; readonly "claim_boundary": string; readonly "default_policy": { readonly "backup_required": true; readonly "destructive_migration": "deny"; readonly "implicit_write_upgrade": "deny"; readonly "receipt_required": true; readonly "unknown_version": "reject"; }; readonly "families": ReadonlyArray<{ readonly "current_write_version": number; readonly "family": string; readonly "migrations": ReadonlyArray<string>; readonly "minimum_read_version": number; readonly "versions": ReadonlyArray<{ readonly "schema_id": string; readonly "status": "supported_read_only" | "current" | "deprecated"; readonly "version": number; }>; }>; readonly "schema_version": "org.searchright.schema-migration-registry.v1"; };

export type ScreeningDecision = { readonly "agent_provenance": null | string; readonly "confidence": null | number; readonly "decided_at": string; readonly "decision": "include" | "exclude" | "unclear"; readonly "decision_id": string; readonly "eligibility_version": string; readonly "exclusion_reason": null | { readonly "criterion_id": string; readonly "evidence": null | string; readonly "label": string; readonly "reason_id": string; }; readonly "rationale": string; readonly "review_id": string; readonly "reviewer_id": string; readonly "reviewer_kind": "human" | "agent" | "adjudicator"; readonly "round": "title_abstract" | "full_text"; readonly "subject_id": string; };

export type ScreeningPolicy = { readonly "adjudication_rule": string; readonly "agent_authority": "advisory_only" | "include_only" | "exclusion_with_human_confirmation"; readonly "full_text_reviewers": number; readonly "independent_blinding": boolean; readonly "minimum_agent_sensitivity": number | null; readonly "schema_version": "org.searchright.screening-policy.v1"; readonly "title_abstract_reviewers": number; };

export type SearchRun = { readonly "completed_at": string | null; readonly "purpose": string; readonly "receipts": ReadonlyArray<SourceReceipt>; readonly "review_id": string; readonly "run_id": string; readonly "schema_version": "org.searchright.search-run.v1"; readonly "started_at": string; readonly "supersedes_run_id": string | null; };

export type SearchStrategy = { readonly "dialect": "pub_med" | "ovid_medline" | "embase" | "europe_pmc" | "cinahl_ebsco" | "psyc_info_ovid" | "scopus" | "web_of_science" | "crossref" | "open_alex" | "clinical_trials_gov" | "generic_boolean" | { readonly "custom": string; }; readonly "limits": { readonly "filters": ReadonlyArray<string>; readonly "languages": ReadonlyArray<string>; readonly "publication_date": null | { readonly "from_year": null | number; readonly "to_year": null | number; }; readonly "publication_types": ReadonlyArray<string>; readonly "rationale": ReadonlyArray<string>; }; readonly "notes": ReadonlyArray<string>; readonly "query": QueryAst; readonly "review_id": string; readonly "schema_version": "org.searchright.search-strategy.v1"; readonly "source_id": string; readonly "strategy_id": string; readonly "translated_from": null | string; };

export type SearchValidation = { readonly "approved_by": string | null; readonly "approved_for_execution": boolean; readonly "minimum_seed_recall": number | null; readonly "press_reviews": ReadonlyArray<{ readonly "decision": string; readonly "findings": ReadonlyArray<{ readonly "element": "translation_of_question" | "boolean_and_proximity" | "subject_headings" | "text_words" | "spelling_syntax_and_lines" | "limits_and_filters"; readonly "finding_id": string; readonly "message": string; readonly "recommendation": string; readonly "resolved": boolean; readonly "severity": "note" | "advisory" | "major" | "critical"; }>; readonly "press_review_id": string; readonly "reviewed_at": string; readonly "reviewer_id": string; readonly "strategy_id": string; readonly "strategy_version": string; }>; readonly "review_id": string; readonly "schema_version": "org.searchright.search-validation.v1"; readonly "seed_records": ReadonlyArray<{ readonly "identifier": string; readonly "relevance_basis": string; readonly "retrieved": boolean; readonly "seed_id": string; readonly "source_id": string; }>; readonly "strategy_id": string; readonly "strategy_version": string; readonly "translation_assessments": ReadonlyArray<{ readonly "human_approved": boolean; readonly "maximum_material_warnings": number; readonly "notes": ReadonlyArray<string>; readonly "observed_material_warnings": number; readonly "strategy_id": string; readonly "target_dialect": string; }>; };

export type SourceReceipt = { readonly "cache_hits": number; readonly "cache_writes": number; readonly "compiler_version": string; readonly "endpoint": string | null; readonly "executed_at": string; readonly "execution_mode": "fixture" | "replay" | "live" | "mixed-fixture-replay" | "mixed-live-replay"; readonly "pages_retrieved": number; readonly "policy": { readonly "cache_write_enabled": boolean; readonly "live_enabled": boolean; readonly "max_pages": number; readonly "max_records": number; readonly "max_response_bytes"?: number | null; readonly "max_retries": number; readonly "min_interval_ms": number; readonly "replay_enabled": boolean; readonly "retry_base_delay_ms"?: number | null; readonly "retry_max_delay_ms"?: number | null; readonly "timeout_seconds": number; readonly "total_timeout_seconds"?: number | null; }; readonly "provider_id": string; readonly "provider_version": string; readonly "query_hash": string; readonly "receipt_id": string; readonly "records_retrieved": number; readonly "result_digest": string; readonly "review_id": string; readonly "run_id": string; readonly "schema_version": "org.searchright.source-receipt.v1"; readonly "source_label": string; readonly "strategy_id": string; readonly "warnings": ReadonlyArray<string>; };

export type SourcerightParityReport = { readonly "blockers": ReadonlyArray<string>; readonly "case_ids": ReadonlyArray<string>; readonly "cutover_ready": boolean; readonly "dimensions": ReadonlyArray<{ readonly "approved_difference_id": string | null; readonly "dimension": string; readonly "equivalent": boolean; readonly "legacy_digest": string; readonly "note": string; readonly "shared_digest": string; }>; readonly "generated_at": string; readonly "legacy_revision": string; readonly "schema_version": "org.searchright.sourceright-parity-report.v1"; readonly "shared_revision": string; };

export type StandardAssessment = { readonly "assessed_at": string; readonly "assessed_by": string; readonly "items": ReadonlyArray<{ readonly "evidence": ReadonlyArray<string>; readonly "item_id": string; readonly "note": string; readonly "state": "met" | "partial" | "unmet" | "not_applicable" | "not_assessed"; }>; readonly "pack_id": string; readonly "pack_version": string; readonly "review_id": string; readonly "schema_version": "org.searchright.standard-assessment.v1"; };

export type StandardPack = { readonly "family": "prisma2020" | "prisma_s" | "prisma_sc_r" | "prisma_lsr" | "prisma_p" | "press2015" | "cochrane_handbook" | "mecir" | "jbi" | "campbell" | { readonly "custom": string; }; readonly "items": ReadonlyArray<{ readonly "crosswalks": ReadonlyArray<string>; readonly "item_id": string; readonly "label": string; readonly "requirement_summary": string; readonly "scope": string; }>; readonly "pack_id": string; readonly "provenance_note": string; readonly "schema_version": "org.searchright.standard-pack.v1"; readonly "source": string; readonly "version": string; };

export type StudyGraph = { readonly "links": ReadonlyArray<{ readonly "asserted_at": string; readonly "asserted_by": string; readonly "confidence": number; readonly "evidence": ReadonlyArray<string>; readonly "from_id": string; readonly "link_id": string; readonly "relationship": "record_describes_report" | "report_of_study" | "protocol_for_study" | "secondary_analysis_of_study" | "updates_report" | "duplicate_of" | { readonly "custom": string; }; readonly "to_id": string; }>; readonly "reports": ReadonlyArray<{ readonly "doi": string | null; readonly "pmid": string | null; readonly "publication_year": number | null; readonly "record_ids": ReadonlyArray<string>; readonly "registry_ids": ReadonlyArray<string>; readonly "report_id": string; readonly "retrieval_attempts": ReadonlyArray<{ readonly "attempt_id": string; readonly "attempted_at": string; readonly "content_digest": string | null; readonly "method": string; readonly "note": string; readonly "report_id": string; readonly "rights_basis": string | null; readonly "status": "not_attempted" | "retrieved" | "not_retrieved" | "restricted" | "unavailable" | "awaiting_contact" | { readonly "other": string; }; }>; readonly "title": string; }>; readonly "review_id": string; readonly "schema_version": "org.searchright.study-graph.v1"; readonly "studies": ReadonlyArray<{ readonly "label": string; readonly "notes": ReadonlyArray<string>; readonly "registration_ids": ReadonlyArray<string>; readonly "report_ids": ReadonlyArray<string>; readonly "study_design": string | null; readonly "study_id": string; }>; };

export type TelemetryPolicy = { readonly "approved_by": string | null; readonly "attribute_allowlist": ReadonlyArray<string>; readonly "enabled": boolean; readonly "endpoint": string | null; readonly "policy_id": string; readonly "prohibited_attributes": ReadonlyArray<string>; readonly "retention_days": number; readonly "sampling_per_million": number; readonly "schema_version": "org.searchright.telemetry-policy.v1"; };

export type TenantPolicy = { readonly "allowed_regions": ReadonlyArray<string>; readonly "allowed_scopes": ReadonlyArray<"review_read" | "review_write" | "search_execute" | "screening_recommend" | "screening_decide" | "tenant_admin" | "external_write">; readonly "approved_by": string; readonly "cross_tenant_aggregation_allowed": false; readonly "external_model_processing_allowed": boolean; readonly "maximum_concurrent_tasks": number; readonly "policy_version": string; readonly "restricted_full_text_persistence_allowed": boolean; readonly "schema_version": "org.searchright.tenant-policy.v1"; readonly "tenant_id": string; };

export type WorkflowTraceActorKind = "human" | "tool" | "agent";

export type WorkflowTraceStage = "draft" | "plan_approved" | "strategy_validated" | "execution_approved" | "search_executed" | "deduplicated" | "title_abstract_complete" | "full_text_complete" | "reported" | "update_planned";

export type WorkflowTraceTransition = { readonly "actor_id": string; readonly "actor_kind": WorkflowTraceActorKind; readonly "approved": boolean; readonly "evidence_ids": ReadonlyArray<string>; readonly "from": WorkflowTraceStage; readonly "occurred_at": string; readonly "to": WorkflowTraceStage; readonly "transition_id": string; };

export type WorkflowTrace = { readonly "initial_stage": WorkflowTraceStage; readonly "review_id": string; readonly "schema_version": "org.searchright.workflow-trace.v1"; readonly "transitions": ReadonlyArray<WorkflowTraceTransition>; };

export const CONTRACT_IDS = ["access-decision", "access-request", "agent-workflow", "architecture-policy", "audit-event", "audit-event-registry", "backup-manifest", "benchmark-report", "bibliographic-record", "compiled-strategy", "component-health", "consumer-contract-suite", "data-handling-decision", "data-handling-request", "data-lifecycle-decision", "data-lifecycle-request", "diagnostic", "discovery-run", "document-evidence", "evidence-debt", "execution-envelope", "gate-catalog", "github-control-plane-apply-summary", "github-issue-hierarchy", "github-issue-hierarchy-v2", "github-project", "github-repository-settings", "incident-record", "institutional-policy", "integration-passport", "integration-release-train", "interchange-receipt", "licensed-adapter", "living-update", "named-filter-pack", "native-search-strategy", "prisma-flow", "protocol-amendment", "provider-component", "provider-component-release-signature", "provider-component-trust-policy", "provider-manifest", "provider-page", "provider-policy-set", "query-ast", "ranking-calibration", "recovery-rehearsal", "redaction-profile", "release-rehearsal", "research-object-handoff-plan", "review-bundle-manifest", "review-plan", "review-state-snapshot", "schema-migration-plan", "schema-migration-registry", "screening-decision", "screening-policy", "search-run", "search-strategy", "search-validation", "source-receipt", "sourceright-parity-report", "standard-assessment", "standard-pack", "study-graph", "telemetry-policy", "tenant-policy", "workflow-trace"] as const;
