[package]
name = "searchright-cli"
description = "Command-line interface for Searchright."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "searchright"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_mangen.workspace = true
searchright = { path = "../searchright", version = "=0.1.0-alpha.1" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[lints]
workspace = true
